### ISSUE TITLE
Package is missing apc.php file.

### ISSUE THREAD

**Issue by FancyFane** [iuscommunity-pkg/php55u-pecl-apcu#2]
Hi IUS Team,

It appears that the apc.php file is missing from the /usr documentation directory. This file is useful for controling and troubleshooting the apcu package. Searching further it appears to now have an ambigious name that is harder to find:

```
# yum search apcu-panel55u
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * ius: dfw.mirror.rackspace.com
========================================================== N/S Matched: apcu-panel55u ==========================================================
apcu-panel55u.noarch : APCu control panel

  Name and summary matches only, use "search all" for everything.
```

This package provides the needed file (renamed to index.php from previous names); but it is not apparent that this package is part of the php55u suite; doing a broad search for php55u you would never know this was a related package. In addition my configuration is using nginx + php55u-fpm. Installing this package gave me dependencies for httpd and php55u (neither are needed for my configuration)

```
Dependencies Resolved

================================================================================================================================================
 Package                             Arch                         Version                                      Repository                  Size
================================================================================================================================================
Installing:
 apcu-panel55u                       noarch                       4.0.7-3.ius.centos6                          ius                         15 k
Installing for dependencies:
 httpd                               x86_64                       2.2.15-39.el6.centos                         base                       825 k
 php55u                              x86_64                       5.5.21-1.ius.centos6                         ius                        2.6 M

Transaction Summary
================================================================================================================================================
Install       3 Package(s)

Total download size: 3.4 M
Installed size: 12 M
Is this ok [y/N]: 
```

Would it be possible to rename this package to something like php55u-pecl-apcu-pannel with a description that is also more descriptive to help admins find this. Also,could this package also change the dependancy from httpd and php55u to the more specific package of php55u-pecl-apcu. This would allow for nginx or apache configurations.

**Comment by b-harper** [comment]
Hello FancyFane,

Thanks for taking the time to submit this issue.  With sub-packages like apcu-panel, emac-git, mod_ssl and tkinter, our naming schema does not apply cleanly.  Historically, we have taken the approach of trying not to get to far from upstream even if that means having weird names.  Both Fedora and EL7 call the sub-package in question, apcu-panel.  

About requiring Apache, I think that might be worth looking into.  Apache is required as apcu-panel provides more than just that index.php file, but also an Apache configuration file:

```
# rpm -qpl https://dl.iuscommunity.org/pub/ius/stable/Redhat/6/x86_64/apcu-panel55u-4.0.7-3.ius.el6.noarch.rpm
/etc/apcu-panel
/etc/apcu-panel/conf.php
/etc/httpd/conf.d/apcu-panel.conf
/usr/share/apcu-panel
/usr/share/apcu-panel/index.php
```

Without looking into this too far, I see a few different options:

1) We keep the package as is to stay inline within upstream.
2) We removed the Apache configuration file, so the requirement for Apache is not needed.
3) Move the Apache configuration to /usr/share/doc/ so it would still be available, but not a requirement.  
4) Split this package into Apache and Nginx specific packages.  

There might be a few more options, those are the ones that came to mind.  

-Ben

**Comment by FancyFane** [comment]
Hi Ben, 

Just as a reminder, we won't need the php55u package as a dependancy either. My current setup is running without it as I'm using php-fpm55u instead. Maybe we can also remove that dependancy as well. I like the idea of moving the files into the /usr/share/doc location. 

-Fane

**Comment by b-harper** [comment]
After giving this some more thought, I like the idea of moving the the Apache configuration to /usr/share/doc/ and then remove the requirement for mod_php and Apache.  We might need to add some comments to the Apache configuration stating that mod_php is required.  

Thoughts?  Anyone got a better idea?

**Comment by cgtx** [comment]
I think it makes sense to drop the panel subpackage and make apc.php a %doc file in the main package.  The apache config file is unnecessary in my opinion.  All the config does is add a path alias and restrict access, which are two things that most people who want to use this will also want to further customize.  Additionally, any webserver that can do php can serve the page.  So we have an example apache config, do we also need to add an nginx config?  What about lighttpd?  Where do we draw the line?

**Comment by b-harper** [comment]
Opening this discussion to the mailing list:

https://lists.launchpad.net/ius-community/msg01412.html

**Comment by slashterix** [comment]
@cgtx 

> make apc.php a %doc file in the main package

I assume you mean php-common? That gets my vote :+1:

**Comment by cgtx** [comment]
@slashterix No, I meant putting it in as a %doc in the main portion of php55u-pecl-apcu, then removing the panel subpackage.

**Comment by b-harper** [comment]
For those interested how Fedora is solving this issue, see Remi's reply in the mailing list thread:

https://lists.launchpad.net/ius-community/msg01413.html

After reading through the replies, I have another idea that might work better.  We could leave the apcu-panel55u as is a solution for Apache users.  Then we would also add the single php file and maybe the panel configuration files as %doc in the php55u-pecl-apcu package.  This would allow Apache users to get the same experience and extend some flexibility for people using other web servers to roll their own configuration.

**Comment by b-harper** [comment]
In an effort to keep the ball rolling, I went ahead and created a test RPM based on my idea on the previous comment.  The packages will be hitting our development repos after tonight's automation run.  If you are using the ius-release package you can use the development repos like the following:

```
# yum search foo-bar --enablerepo=ius-dev
```

We would appreciate feedback regarding this test package.

**Comment by FancyFane** [comment]
Hi team, 

I was able to spin up a cloud box and test this functionality. This looks like a good solution for the task at hand. I was able to install apc and nginx without having to install apache. I was also able to place the apc.php file into the document root and access the file. Below I'm including some output to show this was a valid solution. 

200 OK with the new apc.php file from the documentation:

```
[root@cloud-server-02 ~]# curl -si http://localhost/apc.php | head -15
HTTP/1.1 200 OK
Server: nginx/1.0.15
Date: Wed, 10 Jun 2015 22:01:07 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/5.5.25
Cache-Control: no-store, no-cache, must-revalidate
Cache-Control: post-check=0, pre-check=0
Pragma: no-cache

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head><title>APCu INFO (cloud-server-02) (127.0.0.1)</title>
<style><!--
```

No requirement to install apache when its not needed:

```
[root@cloud-server-02 ~]# rpm -qa | egrep 'php|nginx|httpd'
php55u-xml-5.5.25-1.ius.centos6.x86_64
php55u-common-5.5.25-1.ius.centos6.x86_64
php55u-pecl-jsonc-1.3.7-1.ius.centos6.x86_64
nginx-filesystem-1.0.15-11.el6.noarch
nginx-1.0.15-11.el6.x86_64
php55u-pecl-apcu-4.0.7-4.ius.centos6.x86_64
php55u-process-5.5.25-1.ius.centos6.x86_64
php55u-cli-5.5.25-1.ius.centos6.x86_64
php55u-pear-1.9.5-2.ius.centos6.noarch
php55u-fpm-5.5.25-1.ius.centos6.x86_64
```

Please let me know if further testing is needed before this is pushed to production.

Regards,
Fane

**Comment by b-harper** [comment]
Hello @FancyFane,

Thanks for feedback.  We will proceed with making this change to both php55u-pecl-apcu and php56u-pecl-apcu.  The updated packages will be hitting the stable repos after tonight's automation run.  

-Ben
